springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true
    swagger-ui:
      base-url: /documentacion
swagger:
  base-package: 'com.umdev.commons'
  api-info:
    title: 'UMDEV Commons'
    description: 'Commons library for UMDEV projects'
    contact:
      name: 'Luis Antonio Mata'
      url: 'www.prx.test'
      email: 'luis.antonio.mata@gmail.com'

security:
  discovery:
    client:
      name: ${backbone-alias}
      trust-store-file: ${backbone-truststore-location}
      trust-store-password: ${backbone-truststore-password}
      trust-store-type: ${backbone-truststore-type}
      max-total-connections: 10
      max-connections-per-host: 10
